import type { ReportDefinition } from '../types';

/** Ledger receipts — AI-friendly example: UPI receipts in a date range. */
export const financeReceiptsReport: ReportDefinition = {
  id: 'finance_receipts',
  title: 'Finance Receipts',
  description: 'Verified and pending ledger receipts by payment method and date.',
  permission: 'report',
  baseTable: 'finance_entries',
  societyColumn: 'society_id',
  defaultSort: { field: 'transaction_date', direction: 'desc' },
  defaultPageSize: 50,
  rowLimit: 2500,
  columns: [
    { key: 'transaction_date', label: 'Date', type: 'date', field: 'transaction_date', format: 'date', sortable: true },
    { key: 'title', label: 'Title', type: 'string', field: 'title', searchable: true, sortable: true },
    { key: 'record_mode', label: 'Mode', type: 'string', field: 'record_mode', searchable: true, sortable: true },
    { key: 'destination', label: 'Destination', type: 'string', field: 'destination', searchable: true, sortable: true },
    {
      key: 'payment_method',
      label: 'Method',
      type: 'string',
      field: 'payment_method',
      searchable: true,
      sortable: true,
    },
    {
      key: 'payment_status',
      label: 'Status',
      type: 'string',
      field: 'payment_status',
      searchable: true,
      sortable: true,
    },
    {
      key: 'total_amount',
      label: 'Amount',
      type: 'number',
      field: 'total_amount',
      format: 'money',
      sortable: true,
      aggregate: 'sum',
    },
    {
      key: 'aggregate_flat_count',
      label: 'Flats',
      type: 'number',
      field: 'aggregate_flat_count',
      sortable: true,
      aggregate: 'sum',
      defaultVisible: false,
    },
    { key: 'transaction_id', label: 'Txn ID', type: 'string', field: 'transaction_id', searchable: true, defaultVisible: false },
    { key: 'notes', label: 'Notes', type: 'string', field: 'notes', searchable: true, defaultVisible: false },
  ],
  filters: [
    { key: 'period', label: 'Transaction period', type: 'date_range', field: 'transaction_date' },
    {
      key: 'payment_method',
      label: 'Payment method',
      type: 'select',
      field: 'payment_method',
      operator: 'eq',
      options: [
        { value: 'upi', label: 'UPI' },
        { value: 'cash', label: 'Cash' },
        { value: 'bank_transfer', label: 'Bank Transfer' },
        { value: 'cheque', label: 'Cheque' },
        { value: 'card', label: 'Card' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      key: 'payment_status',
      label: 'Status',
      type: 'select',
      field: 'payment_status',
      operator: 'eq',
      options: [
        { value: 'verified', label: 'Verified' },
        { value: 'pending', label: 'Pending' },
        { value: 'rejected', label: 'Rejected' },
      ],
    },
    {
      key: 'record_mode',
      label: 'Record mode',
      type: 'select',
      field: 'record_mode',
      operator: 'eq',
      options: [
        { value: 'flats_only', label: 'Flats only' },
        { value: 'outsider_only', label: 'Outsider only' },
        { value: 'society_pool', label: 'Society pool' },
        { value: 'mixed', label: 'Mixed' },
      ],
    },
    { key: 'destination', label: 'Destination', type: 'text', field: 'destination', operator: 'ilike' },
  ],
};
