import type { ReportDefinition } from '../types';

export const maintenancePaymentsReport: ReportDefinition = {
  id: 'maintenance_payments',
  title: 'Maintenance Payments',
  description: 'Maintenance receipts by flat, method, status, and due period.',
  permission: 'report',
  baseTable: 'maintenance_payments',
  societyVia: { relation: 'maintenance_charges', column: 'society_id' },
  joins: [{ relation: 'maintenance_charges!inner', columns: ['id', 'title', 'society_id'] }],
  defaultSort: { field: 'payment_date', direction: 'desc' },
  defaultPageSize: 50,
  rowLimit: 2500,
  columns: [
    { key: 'flat_number', label: 'Flat', type: 'string', field: 'flat_number', searchable: true, sortable: true },
    { key: 'resident_name', label: 'Resident', type: 'string', field: 'resident_name', searchable: true },
    {
      key: 'charge_title',
      label: 'Charge',
      type: 'string',
      field: 'maintenance_charges.title',
      searchable: true,
      sortable: true,
    },
    { key: 'due_date', label: 'Due date', type: 'date', field: 'due_date', format: 'date', sortable: true },
    { key: 'payment_date', label: 'Paid on', type: 'date', field: 'payment_date', format: 'date', sortable: true },
    {
      key: 'payment_method',
      label: 'Method',
      type: 'string',
      field: 'payment_method',
      searchable: true,
      sortable: true,
    },
    {
      key: 'payment_status',
      label: 'Status',
      type: 'string',
      field: 'payment_status',
      searchable: true,
      sortable: true,
    },
    {
      key: 'amount',
      label: 'Amount',
      type: 'number',
      field: 'amount',
      format: 'money',
      sortable: true,
      aggregate: 'sum',
    },
    { key: 'transaction_id', label: 'Txn ID', type: 'string', field: 'transaction_id', searchable: true, defaultVisible: false },
    { key: 'notes', label: 'Notes', type: 'string', field: 'notes', searchable: true, defaultVisible: false },
  ],
  filters: [
    { key: 'period', label: 'Payment period', type: 'date_range', field: 'payment_date' },
    { key: 'due_period', label: 'Due period', type: 'date_range', field: 'due_date' },
    {
      key: 'payment_method',
      label: 'Payment method',
      type: 'select',
      field: 'payment_method',
      operator: 'eq',
      options: [
        { value: 'upi', label: 'UPI' },
        { value: 'cash', label: 'Cash' },
        { value: 'bank_transfer', label: 'Bank Transfer' },
        { value: 'cheque', label: 'Cheque' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      key: 'payment_status',
      label: 'Status',
      type: 'select',
      field: 'payment_status',
      operator: 'eq',
      options: [
        { value: 'verified', label: 'Verified' },
        { value: 'pending', label: 'Pending' },
        { value: 'rejected', label: 'Rejected' },
        { value: 'unpaid', label: 'Unpaid' },
      ],
    },
    { key: 'flat_number', label: 'Flat', type: 'text', field: 'flat_number', operator: 'ilike' },
  ],
};
